seccomp: fix build failure on mips (use _MIP_SIM tests)
glibc's sysdeps/mips/sgidefs.h unconditionally mips _ABI* enum values:
  #define _ABIO32                1
  #define _ABIN32                2
  #define _ABI64                 3
  #define _ABIO64                4

This causes build failures on multiple definitions:
  In file included from security.c:9:
  seccomp-bpf.h:73:28: error: redefinition of 'seccomp_bpf_blks_base'
     73 | static const unsigned char seccomp_bpf_blks_base[] = {
        |                            ^~~~~~~~~~~~~~~~~~~~~

The fix is to test current ABI against _MIPS_SIM.

Fixed-by: Manuel Lauss
Bug: https://bugs.gentoo.org/795075
Signed-off-by: Sergei Trofimovich <slyfox@gentoo.org>